apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-test-app
  labels:
    app: harness-test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: harness-test-app
  template:
    metadata:
      labels:
        app: harness-test-app
    spec:
      containers:
      - name: harness-container
        image: <+artifacts.sidecars.harness_app_image.image>
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: harness-test-service
spec:
  type: LoadBalancer
  selector:
    app: harness-test-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
